#1.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "unstable"
          purs-tidy: "latest"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Install dependencies
        run: |
          if [ -f "bower.json" ]; then
            npm install bower pulp
            bower install
            pulp build -- "--strict"
            pulp test -- "--strict"
          fi
          bower install
          spago install

      - name: Build source (pulp)
        run: |
          pulp build -- '--censor-lib --strict'
          rm -rf output

      - name: Build source (spago)
        run: spago build --no-install --purs-args '--censor-lib --strict'

      - name: Check formatting
        run: purs-tidy check src test
